---

image: docker:latest

services:
  - docker:dind
build:
 stage: build
 script:
  - docker build -t send .
  - docker tag send awserv/firefox:14.02
  - docker login -u "awserv" -p "$DOCKER_HUB"
  - docker push awserv/firefox:14.02
# only:
#    changes:
#     - dockerfile
#     - app/
#     - .README.md
#- docker run sent /send/
